export default {
  appCartRoot: {
    flex: "1 1 auto",
    height: "0",
    border: "solid 1px #eeeeee",
    display: "flex",
    borderRadius: "4px",
    flexDirection: "column",
    backgroundColor: "#f2f2f2",
    position: "relative",
  },
  appCartButton: {
    marginTop: "10px",
    cursor: "pointer",
  },
  cartButton: {
    width: "100%",
    height: "100%",
    border: "none",
    overflow: "hidden",
    fontSize: "16px",
    minHeight: "41px",
    userSelect: "none",
    borderRadius: "4px",
    transitionDuration: "200ms",
    transitionProperty: "background-color, color",
    background: "rgb(255, 224, 51)",
    fontWeight: "600",
    color: "black",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  yellowColor: {
    color: "#b29c23",
  },
  appCartContent: {
    flex: "1 1 auto",
    display: "flex",
    overflowX: "hidden",
    overflowY: "auto",
    flexDirection: "column",
  },
  appCartMeta: {
    flex: "0 0 auto",
    display: "flex",
    padding: "14px 20px 16px 20px",
    borderTop: "solid 1px #e3e3e3",
  },
  appCartTopLine: {
    flex: "0 0 24px",
    display: "flex",
    padding: "23px 20px 16px 20px",
    boxSizing: "content-box",
    alignItems: "center",
  },
  appCartEmptyCart: {
    width: "170px",
    color: "#b0b0b0",
    margin: "auto",
    fontSize: "15px",
    textAlign: "center",
  },
  appCartDeliveryTime: {
    flex: "1 1 auto",
  },
  appCartTotalPrice: {
    flex: "1 1 auto",
  },
  appCartDeliveryTimeTitle: {
    color: "#b0b0b0",
    padding: "1px 0 3px 0",
    fontSize: "14px",
  },
  appCartDeliveryTimeValue: {
    padding: "2px 0",
    fontSize: "25px",
  },
  appCartPencil: {
    width: "14px",
    height: "14px",
    margin: "2px 0 2px 8px",
    display: "inline-block",
    backgroundSize: "100%",
    backgroundImage:
      "url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTQiIGhlaWdodD0iMTQiIHZpZXdCb3g9IjAgMCAxNCAxNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTEuNzY1IDUuMDlsLTIuOTEtMi45My02Ljk2NCA3LjAwOCAyLjkxIDIuOTI5IDYuOTY0LTcuMDA4em0tOC4yMSA4LjI2MmwtMi45MTEuNjI4Yy0uNDE2LjEwNC0uNzI4LS4yMS0uNjI0LS42MjhsLjcyOC0yLjkyOGMwLS4xMDUuMTA0LS4yMS4xMDQtLjIxbDIuOTEgMi45MjljMCAuMTA1LS4xMDQuMTA1LS4yMDguMjF6bTEwLjI5LTEwLjI1YS41MDguNTA4IDAgMCAwIDAtLjczMkwxMS42Ni4xNzNjLS4yMDgtLjIwOS0uNTItLjIwOS0uNzI3LS4xMDRMOS43OSAxLjIxOWwyLjkxIDIuOTI5IDEuMTQ0LTEuMDQ2eiIgZmlsbD0iIzAwMCIgZmlsbC1ydWxlPSJub256ZXJvIi8+PC9zdmc+)",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
  },
  appCartItemInfo: {
    flex: "1 1 60%",
  },
  appCartItemQuantityContainer: {
    flex: "0 1 10%",
    color: "#b0b0b0",
    height: "35px",
    margin: "-10px 0",
    position: "relative",
    minWidth: "35px",
    fontSize: "14px",
    textAlign: "center",
    background: "#f2f2f2",
    "&:hover": {
      "& $appCartItemIncrement": {
        border: "1px solid #c0c0c0",
        display: "block",
        zIndex: "1",
        background: "linear-gradient(-180deg, #ffffff 0%, #f5f5f5 100%)",
        boxShadow: "0 1px 8px 0 rgba(0, 0, 0, 0.1)",
      },
      "& $appCartItemQuantity": {
        border: "1px solid #c0c0c0",
        display: "block",
        zIndex: "1",
        background: "linear-gradient(-180deg, #ffffff 0%, #f5f5f5 100%)",
        boxShadow: "0 1px 8px 0 rgba(0, 0, 0, 0.1)",
        borderTop: "none",
        borderBottom: "none",
      },
      "& $appCartItemDecrement": {
        border: "1px solid #c0c0c0",
        display: "block",
        zIndex: "1",
        background: "linear-gradient(-180deg, #ffffff 0%, #f5f5f5 100%)",
        boxShadow: "0 1px 8px 0 rgba(0, 0, 0, 0.1)",
      },
    },
  },
  appCartItemPrice: {
    flex: "0 1 20%",
    fontSize: "14px",
    textAlign: "right",
  },
  appCartItemName: {
    //'fontSize': '16px',
    marginRight: "4px",
  },
  appCartItemWeight: {
    color: "#b0b0b0",
    fontSize: "12px",
    whiteSpace: "nowrap",
  },
  appCartItemQuantity: {
    height: "35px",
    lineHeight: "35px",
  },
  appCartItem: {
    padding: "10px 20px",
  },
  appCartItemOptions: {
    color: "#b0b0b0",
    fontSize: "13px",
    marginTop: "4px",
    lineHeight: "18px",
  },
  appCartDivider: {
    height: "1px",
    margin: "10px 20px",
    backgroundColor: "#e3e3e3",
  },
  appCartDeliveryFee: {
    padding: "10px 20px",
    paddingBottom: "20px",
    display: "flex",
    alignItems: "center",
  },
  appCartDeliveryFeeName: {
    //"fontSize": "16px",
    marginRight: "auto",
  },
  appCartDeliveryFeeValue: {
    fontSize: "14px",
    textAlign: "right",
  },
  appCartPromoItemName: {
    flex: "1 1 70%",
    //"fontSize": "16px",
    marginRight: "auto",
  },
  appCartPromoItemAmount: {
    flex: "0 1 30%",
    color: "#67b893",
    fontSize: "14px",
    textAlign: "right",
  },
  appCartItemIncrement: {
    width: "100%",
    height: "35px",
    cursor: "pointer",
    bottom: "100%",
    display: "none",
    position: "absolute",
    fontSize: "20px",
    lineHeight: "35px",
    fontWeight: "bold",
  },
  appCartItemDecrement: {
    top: "100%",
    width: "100%",
    height: "35px",
    cursor: "pointer",
    display: "none",
    position: "absolute",
    fontSize: "20px",
    lineHeight: "35px",
    fontWeight: "bold",
  },
  appCartItemRemove: {
    color: "#8b0000 !important",
  },
};
